# Generated by Django 6.0.1 on 2026-01-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ttac.ticketresale')),
            ],
        ),
    ]
