# Generated by Django 6.0.1 on 2026-01-29 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttac', '0003_walletpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['show_time']},
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('theatre', 'show_time'), name='unique_show_per_theatre_time'),
        ),
    ]
