# Generated by Django 6.0.1 on 2026-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttac', '0004_alter_show_options_show_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
